### PR TITLE
Fixed some errors.

### PR DESCRIPTION
**Pull request by IceReaper**

### CODE REVIEW

**Review by optimus-code — APPROVED** [review]
This is great, thanks for the Pull Request! Great to see others willing to help.

**Comment by IceReaper** [comment]
Fun fact: i actualy had the same project going on, just Not yet pushed. Hand translated the source without any tool generating garbage. I can already get ingame so far. Its due to the fact of being a ported jake2 quite similar in source. I just didnt pr that as it would basicaly change all the files as i applied my codestyle. Ill see what i can contribute to get your errors gone.

**Comment by IceReaper** [comment]
I pushed my source here: https://github.com/IceReaper/Quake2Sharp take what you want if you find anything useful ;)

**Comment by optimus-code** [comment]
Funny world :) I thought I was alone in wanting this, hence the automated conversion - converting so many lines of code at once is a huge task and I fixed over 14k errors by hand. I've managed to make further progress but this is a long way off working in any manner, I've likely introduced bugs everywhere too. But that's all the fun eh?

**Pull request merged**
